### ISSUE TITLE
No Horizontal Grid Lines / No Loop Region Highlight

### ISSUE THREAD

**Issue by Zacchino** [lenninst/Nord_BitwigTheme#1]
Hello Lenninst!

First and foremost, I absolutely love your theme. It's so subtle and elegant!

Now, there's 2 small issues I'm seeing (but besides that it's just perfect):
1. There's no Horizontal Grid Lines (separating the tracks in the Arranger), only vertical ones. Is that something that can be fixed?
2. Same thing with the Loop Region, when turned on, there's no way to see within the Arranger where the Loop Region extends. Only the top scroll bar indicates where the region starts and stops. 

Maybe these are limitation from the Theme Editor itself?

**Comment by lenninst** [comment]
Hello, @Zacchino  😊

Thank you so much for your comment and for appreciating the theme. I'm really glad you like it.

I've looked into the issues you mentioned:

1. The absence of horizontal grid lines in the Arranger.
2. The lack of visibility for the loop region in the Arranger.

I've found a solution for these problems. However, I've been quite busy these days and haven't been able to implement it yet. I assure you that I'll fix it as soon as possible.

I appreciate your patience and your feedback, which is very valuable for improving the theme. I'll update this issue as soon as I have the solution implemented.

Best regards. 😁👍

**Comment by Zacchino** [comment]
Oh heck yeah! So much looking forward to it!

Sure sure I'll be patient. Let me know when done and I'll re-install the theme to try it out!

Thank you so so much again, this is a work of art!

**Comment by lenninst** [comment]
Hi @Zacchino 👍 The solution is now ready in the latest GitHub  [release](https://github.com/lenninst/Nord_BitwigTheme/releases) .   Feel free to reinstall the theme and give it a try. Thanks for your patience and kind words. Let me know what you think once you've tested it. Hope you enjoy it! 😊

**Comment by Zacchino** [comment]
OMG This is it! You fixed both these issues perfectly!
Absolutely love the way you highlighted the Tracks & Loop Region in contrast to the Empty Space! Very subtle.

Gosh it's such a pleasure to work on Bitwig with it:
Thanks SO much for taking the time for it 🙏
